export const mapBtn = {
  backgroundColor: "rgba(34, 34, 34,1)",
  color: "rgba(255,255,255,1)",
  border: "4px",
  margin: "10px",
  padding: "0px",
  position: "absolute",
  cursor: "pointer",
  userSelect: "none",
  borderRadius: "2px",
  height: "40px",
  width: "40px ",
  boxShadow: "rgba(0, 0, 0, 0.5) 0px 1px 4px -1px",
  overflow: "hidden",
  bottom: "50%",
  top: "50%",
  right: "0%",
  zIndex: 99,
  transform: "translateX(100%)",
  transform: "translateY(-50%)"
};
